### ISSUE TITLE
Lots of emails from TGTG to continue with the logon 

### ISSUE THREAD

**Issue by dabepp** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#61]
I don't get it, what am I doing wrong? Since yesterday I get those mails every 30 minutes.
If I stop the add-on the mails quit, if I restart it they keep coming.
![Bildschirmfoto 2022-06-20 um 19 30 49](https://user-images.githubusercontent.com/28548283/174653346-731141a4-3d7b-4b2b-893a-ed0653fb83d8.png)

Config:
email: mymail@gmail.com
language: en-US
polling_schedule: '*/10 * * * *'
every_n_minutes: 10

Any inout appreciated!

**Comment by MaxWinterstein** [comment]
Missing a lot of context, so more a less a blind guess:

Did you read the log of the add-on after starting? I guess you did some update to the latest version, that might require a (re-) login.

Did you try to hit the login button of the mail, after it arrived within a short period of time?

**Comment by Florian14490** [comment]
Yes, here the same.
After addon update 2 days ago. Need to re-login. No problem.  But login email is not receiving my mailbox. Restart a few times. No luck. In the morning i see about 5 login emails in mailbox received 2 /3 clock early morning. All of them with login code. But expired.
Yesterday restart addon few times. No emails. Last night/morning I received al the mails around same time as night before. All error because to late.

Haha. Whats happening

**Comment by Dielee** [comment]
What does the logs say ? I tested it, for me login is working normal. Maybe a spamfilter blocks the emails ?

**Comment by dabepp** [comment]
Ok seems a fresh start (Aka uninstall -> Reboot -> Install) solved the issue!

**Comment by MaxWinterstein** [comment]
If you are familiar with email source code and their headers, you might try https://mha.azurewebsites.net/

In my case, those mentioned mails look like this:
![image](https://user-images.githubusercontent.com/5927148/174747044-224bc816-8bf3-4035-98eb-7d6ceacb866d.png)

looks like gmx said: "hold on, wait a little bit"

**Comment by Florian14490** [comment]
Just update the tgtg addon and its working again like a charm. Thnx again, @MaxWinterstein .
Have a nice day
